# Generated by Django 3.2.6 on 2021-08-22 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('type_id', models.IntegerField()),
                ('title', models.CharField(max_length=150)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('description', models.TextField(max_length=500)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('forms', models.ManyToManyField(to='form_app.Form')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_app.form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerQuestion',
            fields=[
                ('option', models.CharField(choices=[('1', 'Strongly Disagree'), ('2', 'Disagree'), ('3', 'Partially Disagree'), ('4', 'Neutral'), ('5', 'Partially Agree'), ('6', 'Agree'), ('7', 'Strongly Agree')], max_length=25)),
                ('comment', models.TextField(blank=True, max_length=1500, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('answer_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_app.answersheet')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_app.question')),
            ],
        ),
    ]
